In [1]:
import warnings
warnings.filterwarnings('ignore')

#### Рассматриваем выборку

Кластеризуем письма на различные темы

In [2]:
from sklearn.datasets import fetch_20newsgroups

In [3]:
train_all = fetch_20newsgroups(subset = 'train')
print(train_all.target_names)

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


Берем простую выборку состоящую из 3 тем, сильно отличающихся друг от друга

In [4]:
simple_dataset = fetch_20newsgroups(subset = 'train',
                                   categories = ['comp.sys.mac.hardware', 
                                                 'soc.religion.christian',
                                                'rec.sport.hockey'])

In [5]:
print(simple_dataset.data[0])

From: erik@cheshire.oxy.edu (Erik Adams)
Subject: HELP!!  My Macintosh "luggable" has lines on its screen!
Organization: Occidental College, Los Angeles, CA 90041 USA.
Distribution: comp
Lines: 20

Okay, I don't use it very much, but I would like for it to keep working
correctly, at least as long as Apple continues to make System software
that will run on it, if slowly :-)

Here is the problem:  When the screen is tilted too far back, vertical
lines appear on the screen.  They are every 10 pixels or so, and seem
to be affected somewhat by opening windows and pulling down menus.
It looks to a semi-technical person like there is a loose connection
between the screen and the rest of the computer.

I am open to suggestions that do not involve buying a new computer,
or taking this one to the shop.  I would also like to not have
to buy one of Larry Pina's books.  I like Larry, but I'm not sure
I feel strongly enough about the computer to buy a service manual
for it.

On a related note:  what

In [6]:
simple_dataset.target

array([0, 0, 1, ..., 0, 1, 2], dtype=int32)

In [7]:
print(simple_dataset.data[-1])

From: dlecoint@garnet.acns.fsu.edu (Darius_Lecointe)
Subject: Re: Sabbath Admissions 5of5
Organization: Florida State University
Lines: 21

I find it interesting that cls never answered any of the questions posed. 
Then he goes on the make statements which make me shudder.  He has
established a two-tiered God.  One set of rules for the Jews (his people)
and another set for the saved Gentiles (his people).  Why would God
discriminate?  Does the Jew who accepts Jesus now have to live under the
Gentile rules.

God has one set of rules for all his people.  Paul was never against the
law.  In fact he says repeatedly that faith establishes rather that annuls
the law.  Paul's point is germane to both Jews and Greeks.  The Law can
never be used as an instrument of salvation.  And please do not combine
the ceremonial and moral laws in one.

In Matt 5:14-19 Christ plainly says what He came to do and you say He was
only saying that for the Jews's benefit.  Your Christ must be a
politician, speaki

In [8]:
print(simple_dataset.data[-2])

From: scialdone@nssdca.gsfc.nasa.gov (John Scialdone)
Subject: CUT Vukota and Pilon!!!
News-Software: VAX/VMS VNEWS 1.41    
Organization: NASA - Goddard Space Flight Center
Lines: 32

I have been to all 3 Isles/Caps tilts at the Crap Centre this year, all Isles
wins and there is no justification for Vukota and Pilon to play for the Isles.
Vukota is absolutely the worst puck handler in the world!! He couldn't hit a
bull in the ass with a banjo!! Al must remember a few years back when Mick 
scored 3 goals in one period against the Caps in a 5-3 Isles win. I was there
and was astonished as was the rest of the crowd. Wake-up Al!!! Years later he's
gotten worse. He's a cheap shot artist and always ends up getting
stupid/senseless penalties. I think he would make a good police officier!!!

As for Pilon, he can't carry the puck out to center ice by himself. He either
makes a bad pass resulting in a turnover, or he attempts to bring the puck 
towards the neutral zone and skates right into an 

In [9]:
print(len(simple_dataset.data))

1777


#### Отбираем признаки

In [10]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [11]:
import sklearn
sklearn.__version__ 

'0.23.1'

Задаем пороги для максимальной max_df и минимальной взвешенной частоты min_df слов

In [12]:
vectorizer = TfidfVectorizer(max_df=500, min_df=10)
matrix = vectorizer.fit_transform(simple_dataset.data)

In [13]:
matrix.shape

(1777, 3767)

Пользуемся аггломеративной кластеризацией, тк можно задать метрику близости и косинусную меру(хороша для текстов)

In [14]:
from sklearn.cluster.hierarchical import AgglomerativeClustering

Алгоритм не поддерживает разреженные матрицы => приводим к плотному виду (matrix.toarray() )

In [15]:
model = AgglomerativeClustering(n_clusters = 3, affinity = 'cosine',
                               linkage = 'complete')
preds = model.fit_predict(matrix.toarray())

In [16]:
print(list(preds))

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [17]:
matrix[0]

<1x3767 sparse matrix of type '<class 'numpy.float64'>'
	with 75 stored elements in Compressed Sparse Row format>

In [18]:
print(vectorizer.get_feature_names())

['00', '000', '01', '02', '03', '030', '0358', '04', '040', '05', '06', '07', '08', '09', '10', '100', '1000', '101', '102', '104', '105', '106', '109', '11', '110', '112', '113', '119', '12', '120', '126', '127', '128', '129', '13', '132', '133', '14', '140', '15', '150', '152', '16', '160', '17', '170', '175', '18', '180', '19', '1987', '1988', '1989', '199', '1990', '1991', '1992', '1993', '1993apr14', '1993apr15', '1993apr16', '1993apr18', '1993apr19', '1993apr20', '1993apr5', '1993apr6', '1d17', '1d20', '1st', '20', '200', '2000', '203', '21', '210', '22', '23', '230', '24', '240', '241', '25', '253', '256', '25mhz', '26', '27', '28', '286', '29', '2nd', '30', '300', '30602', '31', '32', '33', '34', '35', '36', '37', '38', '386', '39', '3rd', '40', '400', '403', '408', '41', '42', '43', '44', '45', '46', '47', '48', '486', '49', '4mb', '4th', '50', '500', '51', '512', '512k', '52', '53', '54', '542', '55', '56', '57', '58', '59', '5of5', '5th', '60', '600', '61', '610', '62', '63'

In [19]:
simple_dataset.data[0]

'From: erik@cheshire.oxy.edu (Erik Adams)\nSubject: HELP!!  My Macintosh "luggable" has lines on its screen!\nOrganization: Occidental College, Los Angeles, CA 90041 USA.\nDistribution: comp\nLines: 20\n\nOkay, I don\'t use it very much, but I would like for it to keep working\ncorrectly, at least as long as Apple continues to make System software\nthat will run on it, if slowly :-)\n\nHere is the problem:  When the screen is tilted too far back, vertical\nlines appear on the screen.  They are every 10 pixels or so, and seem\nto be affected somewhat by opening windows and pulling down menus.\nIt looks to a semi-technical person like there is a loose connection\nbetween the screen and the rest of the computer.\n\nI am open to suggestions that do not involve buying a new computer,\nor taking this one to the shop.  I would also like to not have\nto buy one of Larry Pina\'s books.  I like Larry, but I\'m not sure\nI feel strongly enough about the computer to buy a service manual\nfor it.\n

Приходим к тому, что в данном случае много шума и лучше использовать другой метод

#### KMeans

In [20]:
from sklearn.cluster import KMeans

In [21]:
model = KMeans(n_clusters=3, random_state=42)
preds = model.fit_predict(matrix.toarray())
print(preds)
print(simple_dataset.target)

[0 0 1 ... 0 1 2]
[0 0 1 ... 0 1 2]


In [22]:
# Делаем отображение 1->2, 2->1
mapping = {0 : 0, 1: 1, 2: 2}
mapped_preds = [mapping[pred] for pred in preds]
print(float(sum(mapped_preds != simple_dataset.target)) / len(simple_dataset.target))

0.04727068092290377


In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

Произведем сравнение кластеризации с классификатором

In [24]:
clf = LogisticRegression()
print(cross_val_score(clf, matrix, simple_dataset.target).mean())
print(1 - float(sum(mapped_preds != simple_dataset.target)) / len(simple_dataset.target))

0.9859313182465581
0.9527293190770962


#### Рассмотрим более сложную выборку

Выбираем близкие друг к другу темы

In [25]:
dataset = fetch_20newsgroups(subset = 'train',
                            categories = ['comp.sys.mac.hardware', 'comp.os.ms-windows.misc', 
                                          'comp.graphics'])

In [26]:
matrix = vectorizer.fit_transform(dataset.data)
model = KMeans(n_clusters = 3, random_state = 42)
preds = model.fit_predict(matrix.toarray())
print(preds)
print(dataset.target)

[2 1 0 ... 2 0 2]
[2 1 1 ... 2 0 2]


In [27]:
mapping = {0 : 0, 1: 1, 2: 2}
mapped_preds = [mapping[pred] for pred in preds]
print(float(sum(mapped_preds != dataset.target)) / len(dataset.target))

0.22304620650313747


In [28]:
clf = LogisticRegression()
print(cross_val_score(clf, matrix, dataset.target).mean())

0.9264143264143264


#### SVD + KMeans

In [29]:
from sklearn.decomposition import TruncatedSVD

In [30]:
model = KMeans(n_clusters = 3, random_state  = 42)
svd = TruncatedSVD(n_components = 1000, random_state = 123)
features = svd.fit_transform(matrix)
preds = model.fit_predict(features)
print(preds)
print(dataset.target)

[1 0 2 ... 1 2 1]
[2 1 1 ... 2 0 2]


In [37]:
mapping = {1:2, 0:1, 2:0}
mapped_preds = [mapping[pred] for pred in preds]
print(float(sum(mapped_preds != dataset.target) / len(dataset.target)))

0.29834569309754705


Еще сильнее понижаем размерность пространства признаков

In [32]:
model = KMeans(n_clusters=3, random_state=42)
svd = TruncatedSVD(n_components=200, random_state=123)
features = svd.fit_transform(matrix)
preds = model.fit_predict(features)
print(preds)
print(dataset.target)

[1 2 1 ... 1 1 1]
[2 1 1 ... 2 0 2]


In [41]:
import itertools
def validate_with_mappings(preds, target, dataset):
    permutations = itertools.permutations([0, 1, 2])
    for a, b, c in permutations:
        mapping = {2 : a, 1: b, 0: c}
        mapped_preds = [mapping[pred] for pred in preds]
        print(float(sum(mapped_preds != target)) / len(target))
        
validate_with_mappings(preds, dataset.target, dataset)

0.6782658300057045
0.29834569309754705
0.7992013690815745
0.549343981745579
0.7723901882487165
0.9024529378208785


In [34]:
model = KMeans(n_clusters=3, random_state=42)
svd = TruncatedSVD(n_components=200, random_state=321)
features = svd.fit_transform(matrix)
preds = model.fit_predict(features)
print(preds)
print(dataset.target)
validate_with_mappings(preds, dataset.target, dataset)

[1 2 2 ... 1 2 1]
[2 1 1 ... 2 0 2]
0.6782658300057045
0.29834569309754705
0.7992013690815745
0.549343981745579
0.7723901882487165
0.9024529378208785
